---
- name: Copy hosts file to nodes
  hosts: all
  tasks:
    - name: Copy the hosts file to /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

