---
- name: Setup LoadBalancer Node
  hosts: loadbalancer
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Copy nginx confix
      template:
        src: ../configs/loadbalancer_nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
    
    
    - name: Enable and start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Test nginx conf
      command: nginx -t
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
